### ISSUE TITLE
[Documento] - Ajustes Requisitos do Sistema WEB

### ISSUE THREAD

**Issue by Matheus-Msantos** [Matheus-Msantos/Cultura.i_web#4]
*Data início - Data Fim*
08/03 -  14/03

**Comment by Matheus-Msantos** [comment]
**Arquivo do documento**
[ADO4-PI5-ABNT.docx](https://github.com/Matheus-Msantos/Cultura.i_web/files/8255915/ADO4-PI5-ABNT.docx)

**Comment by Matheus-Msantos** [comment]
**FeedBack**

Para fazer: 
- [ ] Padronizar nome (evento ou produto?)
- [x] Cliente pode editar ou excluir a conta? 
- [x] Revisar atributos no requisito RF2
- [x] Adicionar atributos no requisito RF3
- [x] RF2 - Filtragem de eventos como vai funcionar? Explicar melhor.
- [x] RF4  adicionar atributos
- [x] RF5 revisar 
- [x] RF6 adicionar atributos...
- [x] RFPC1/RFA1 mudar foto para logo 
- [x] RFPC3  colocar atributos
- [x] RFPC1/RFA1 não seria necessário verificar se é produtor ou anunciante, pois seria 2 tabelas diferentes 
- [x] RFPC2/RFA2 tirar requisitos de edição e exclusão de eventos
- [x] Criar requisitos de edição
- [x] Criar requisitos de exclusão de eventos
- [x] RFA1 Criar conta
- [x] RFA3  colocar atributos
- [x] Listar Eventos
- [x] Editar evento
- [x] Excluir evento
- [x] Editar conta
- [x] Excluir conta
- [x] Criar conta anunciante
- [x] Editar conta anunciante
- [x] Excluir conta anunciante
- [x] Modificação do numero dos requisitos
- [x] Editar requisitos de ingressos vendidos
- [x] Ajustar sumário

*Obs:* Talvez seria bom criar uma outra tabela chamada local, relacionado  com a tabela de endereço

**Comment by DrielyGuerreiro** [comment]
- [x] Editar requisito  quantidade de ingressos vendidos. ( VERIFICAR VIABILIDADE)
