### ISSUE TITLE
[Front-end] - Login Producer

### ISSUE THREAD

**Issue by brunopontes90** [Matheus-Msantos/Cultura.i_web#41]
Criar componente de login

**Comment by Matheus-Msantos** [comment]
Layout está todo quebrado:
1. Tem um espaço branco nas extremidades da tela
2. Existe uma rolagem lateral o isso não pode ter 
3. Tem um bloco azul que está estourando 
-----
![Captura de tela 2022-04-30 103001](https://user-images.githubusercontent.com/66855345/166107702-1bdbbacc-62f7-42b8-839f-d669b1c35788.jpg)
![Captura de tela 2022-04-30 103242](https://user-images.githubusercontent.com/66855345/166107712-07652ec9-f142-4c86-b558-99981fe6c5f1.jpg)

**Comment by brunopontes90** [comment]
- Layout ajustado com css do background. 
![image](https://user-images.githubusercontent.com/53492661/166164214-0a8be644-91d7-473e-a4cc-6dbc7a89fcf1.png)
