### ISSUE TITLE
[Front-end] - Register

### ISSUE THREAD

**Issue by brunopontes90** [Matheus-Msantos/Cultura.i_web#43]
Criar componentes para realizar cadastro.

**Comment by Matheus-Msantos** [comment]
*Ajustes para ser feito, a página não está de acordo*
1. O background não está ocupando 100% da tela
2. O background não está de acordo com o protótipo 
-----

![Captura de tela 2022-04-30 203256](https://user-images.githubusercontent.com/66855345/166126043-5f3ee9a1-aeba-4433-ba0b-877130a03b05.jpg)

**Background do protótipo**
 
![Captura de tela 2022-04-30 203543](https://user-images.githubusercontent.com/66855345/166126080-18e87922-65ae-4a20-882d-57364ae3df69.jpg)

**Comment by brunopontes90** [comment]
- Ajustes realixado no background ocupando 100% da tela e sem barra de rolagem
![image](https://user-images.githubusercontent.com/53492661/166164294-15ccc915-e407-4971-9705-841f105a12e9.png)

**Comment by Matheus-Msantos** [comment]
Erro não foi resolvido:
1. barra de rolagem ainda permanece 
2. background ainda não está ocupando 100% da tela
3. cor do background ainda está diferente do layout

Este é o correto:
background: conic-gradient(from 180deg at 50% 50%, rgba(241, 118, 4, 0.19) 0deg, #01318B 125.63deg, rgba(241, 118, 4, 0.19) 360deg);

**Por favor olhar atentamente e seguir o protótipo, testar em resoluções menos igual a 1280px ou 1250px**
----
![Captura de tela 2022-05-01 190704](https://user-images.githubusercontent.com/66855345/166166597-84409405-bbce-46ea-8cc4-c2a7ed41dd5f.jpg)

**Comment by brunopontes90** [comment]
- Ajuste no background conforme solicitado.
- Ponto de observação, **em meu ambiente de desenvolvimento não reproduz o erro informado**. Segue imagem abaixo:
![image](https://user-images.githubusercontent.com/53492661/166167192-c3d8773d-7ffa-4c68-b4e3-810380a7637a.png)

- Ponto de atenção, **background desenvolvido conforme o layout na imagem abaixo.** 
![image](https://user-images.githubusercontent.com/53492661/166167140-b6158e1b-6c1b-4333-b5b9-f73c54cb63df.png)

**Comment by Matheus-Msantos** [comment]
Pagina aprovada!
