### ISSUE TITLE
[Front-end] - Página home

### ISSUE THREAD

**Issue by Matheus-Msantos** [Matheus-Msantos/Cultura.i_web#45]
**Para fazer**
Criar estrutura de códigos, componentes e estilizar a página home

**Comment by brunopontes90** [comment]
- botão de proximo carrossel esta acima do numero
![image](https://user-images.githubusercontent.com/53492661/166164813-64f7cc3d-e0ce-4c29-b5f3-56603e92f315.png)

**Comment by Matheus-Msantos** [comment]
Ajuste feito!
