### ISSUE TITLE
[Front-end] - Página checkout

### ISSUE THREAD

**Issue by brunopontes90** [Matheus-Msantos/Cultura.i_web#59]
**Para fazer?**

- [x] Criar estrutura arquivo HTML
- [x] Estilizar e alinhar itens

**Comment by Matheus-Msantos** [comment]
A tela está de acordo com o layout, mas acho que adaptá-la...

Aqui está minha sugestão
![Captura de tela 2022-05-14 050525](https://user-images.githubusercontent.com/66855345/168417024-42ff41c9-c884-4514-8a91-53d0c784f950.jpg)

- Podemos centralizar todo o conteúdo, esse botão vazando pra fora não ficou legal aqui que ele deve seguir alinhado com o header azul
-  centralizar verticalmente os textos no header
- Diminuir o texto do botão, deixar ele como font-weight: 700; , font-size: 20px;, font-transform: uppercase;
- Tirar o Subtotal, e diminuir o texto do total e deixar as letras em maiúscula 
- colocar um background cinza na lista de pedidos

Qualquer coisa fazemos uma call, para eu explicar melhor :)

**Comment by brunopontes90** [comment]
Itens alinhados da forma que solicitou.
![image](https://user-images.githubusercontent.com/53492661/168479090-d9664d9e-d994-458d-ba51-b2b1a11c0633.png)

Não entendi a parte do background cinza, devo coloca-lo em toda a tela ou apenas no campo onde informa os valores e botão?
Sera colocado na parte selecionada conforma a imagem acima?
